export const assets = [
  {
    name: 'tDAI.s',
    address: 'AS124FuWHWqiWurCvobu5ovTGucWJPa6ouHbGLQ9e7kMwWt2Xsm84',
    symbol: 'tDAI.s',
    decimals: 18,
    balance: undefined,
    isDefault: true,
    dollarValue: undefined,
    originChainId: 0,
  },
  {
    name: 'Wrapped MASSA',
    address: 'AS12FW5Rs5YN2zdpEnqwj4iHUUPt9R4Eqjq2qtpJFNKW3mn33RuLU',
    symbol: 'WMAS',
    decimals: 9,
    balance: undefined,
    isDefault: true,
    dollarValue: undefined,
    originChainId: 0,
  },
  {
    name: 'Massa Tips',
    address: 'AS1R8zaZaGZ7Xcc3NeZ41KCzkUjcurFKn7LKhquMKEKrYFZDxfxr',
    symbol: 'TIPS',
    decimals: 18,
    balance: undefined,
    isDefault: true,
    dollarValue: undefined,
    originChainId: 0,
  },
];
